# Generated by Django 3.2.14 on 2022-07-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
